version: '3.3'

services:
   db:
     build: ./db
     volumes:
       - db_data:/var/lib/postgresql
     environment:
       POSTGRES_PASSWORD: passwørd1234

   discordbot:
     depends_on:
       - db
     build: ./discordbot
     ports:
       - "80:80"
     env_file: 
      - ./discordbot/.env
     environment:
      AUTHLINK: "http://db.nordestgaard.org/"
      DBPASS: passwørd1234
volumes:
    db_data: {}